name = "bunying-api"
main = "src/index.ts"
compatibility_date = "2026-05-01"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "alarmu"
database_id = "aa687aed-6b21-4d3c-a29c-f4f4d09e92f4"

# R2 Bucket binding
[[r2_buckets]]
binding = "AUDIO_BUCKET"
bucket_name = "alarmu-audio"

# Environment variables
[vars]
ADMIN_USERNAME = "admin"
R2_PUBLIC_URL = "https://audio.alarmu.site"

# CORS for local dev
# [dev]
# port = 8787
